esphome:
  name: esp32_6relay
  friendly_name: ESP32 6 Relay Board

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# ---------------- LOGGING ----------------
logger:

# ---------------- HOME ASSISTANT API ----------------
api:
  encryption:
    key: "REPLACE_WITH_YOUR_API_KEY"

# ---------------- OTA ----------------
ota:
  - platform: esphome
    password: "REPLACE_WITH_OTA_PASSWORD"

# ---------------- WIFI ----------------
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "ESP32-6Relay Fallback"
    password: "fallback_password"

captive_portal:

# ---------------- RELAYS (ACTIVE LOW) ----------------
switch:
  - platform: gpio
    name: "Relay 1"
    pin:
      number: GPIO14
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: "Relay 2"
    pin:
      number: GPIO27
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: "Relay 3"
    pin:
      number: GPIO26
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: "Relay 4"
    pin:
      number: GPIO25
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: "Relay 5"
    pin:
      number: GPIO33
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: "Relay 6"
    pin:
      number: GPIO32
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
